name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Change if you're using a different branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: |
          npm install  # No need for 'cd dashboard'

      - name: Build project
        run: |
          npm run build  # No need for 'cd dashboard'

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Needed for deployment permissions
          action: "upload"
          app_location: "."  # Project is now in the root directory
          output_location: "dist"  # Build output folder (from npm run build)
