name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # ✅ Ensure this matches your project requirements

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable  # ✅ Required for Yarn 4
          corepack prepare yarn@4.6.0 --activate  # ✅ Ensure correct Yarn version

      - name: Clean conflicting package files (Yarn vs. NPM)
        run: |
          rm -f package-lock.json  # ✅ Remove NPM lock file to avoid conflicts

      - name: Install dependencies (Using Yarn 4)
        run: |
          yarn install --immutable  # ✅ Ensure a clean dependency installation

      - name: Build project
        run: |
          yarn build  # ✅ Use Yarn build command

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."  
          output_location: "dist"
